"""Tests for GitHub Issues integration."""
import json
from pathlib import Path
from vibeplan.github import format_github_issue


def _setup_plan(tmp_path: Path) -> Path:
    d = tmp_path / "project"
    (d / ".vibeplan").mkdir(parents=True)
    steps = [
        {"id": "1", "name": "Research", "description": "Explore APIs", "status": "done", "tokens": 2000},
        {"id": "2", "name": "Implement", "description": "Build core logic", "status": "pending", "tokens": 5000},
    ]
    budget = {
        "steps": steps,
        "original_prompt": "Build a REST API with FastAPI",
        "answers": {"scope": "backend", "stack": "FastAPI"},
    }
    (d / ".vibeplan" / "budget.json").write_text(json.dumps(budget))
    return d


def test_format_issue_contains_task(tmp_path: Path):
    d = _setup_plan(tmp_path)
    body = format_github_issue(d)
    assert "Build a REST API with FastAPI" in body


def test_format_issue_shows_context(tmp_path: Path):
    d = _setup_plan(tmp_path)
    body = format_github_issue(d)
    assert "**scope:**" in body
    assert "backend" in body
    assert "**stack:**" in body
    assert "FastAPI" in body


def test_format_issue_shows_steps(tmp_path: Path):
    d = _setup_plan(tmp_path)
    body = format_github_issue(d)
    assert "- [x]**Step 1: Research**" in body or "- [x] **Step 1: Research**" in body
    assert "- [ ]**Step 2: Implement**" in body or "- [ ] **Step 2: Implement**" in body


def test_format_issue_includes_descriptions(tmp_path: Path):
    d = _setup_plan(tmp_path)
    body = format_github_issue(d)
    assert "Explore APIs" in body
    assert "Build core logic" in body


def test_format_issue_empty_plan(tmp_path: Path):
    d = tmp_path / "empty"
    (d / ".vibeplan").mkdir(parents=True)
    (d / ".vibeplan" / "budget.json").write_text(json.dumps({"steps": [], "original_prompt": ""}))
    body = format_github_issue(d)
    assert body.strip() != ""


def test_format_issue_generated_tag(tmp_path: Path):
    d = _setup_plan(tmp_path)
    body = format_github_issue(d)
    assert "Generated by vibeplan" in body
