"""GitHub Issues integration — create or preview issues from plan."""
import subprocess
import sys
from pathlib import Path
from typing import Optional

from vibeplan.runner import load_plan


def format_github_issue(project_dir: Path) -> str:
    """Generate a GitHub Issue markdown body from the current plan."""
    data = load_plan(project_dir)
    steps = data.get("steps", [])
    prompt = data.get("original_prompt", "")
    answers = data.get("answers", {})

    lines: list[str] = []
    lines.append("## Task")
    lines.append("")
    lines.append(prompt)
    lines.append("")

    if answers:
        lines.append("## Context")
        lines.append("")
        for k, v in answers.items():
            if k != "original_prompt":
                lines.append(f"- **{k}:** {v}")
        lines.append("")

    lines.append("## Plan")
    lines.append("")
    for s in steps:
        status = "- [x]" if s.get("status") == "done" else "- [ ]"
        budget = f" ({s.get('tokens'):,} tokens)" if s.get("tokens") else ""
        lines.append(f"{status} **Step {s['id']}: {s['name']}**{budget}")
        if s.get("description"):
            lines.append(f"  _{s['description']}_")
    lines.append("")

    lines.append("---")
    lines.append("_Generated by vibeplan_")
    return "\n".join(lines)


def publish_issue(project_dir: Path, title: Optional[str] = None) -> Optional[str]:
    """Create a GitHub Issue using `gh` CLI. Returns the issue URL or None."""
    data = load_plan(project_dir)
    prompt = data.get("original_prompt", "")
    issue_title = title or f"vibeplan: {prompt[:72]}"
    body = format_github_issue(project_dir)

    try:
        result = subprocess.run(
            ["gh", "issue", "create", "--title", issue_title, "--body", body],
            capture_output=True, text=True, timeout=30,
        )
        if result.returncode == 0:
            return result.stdout.strip()
        else:
            print(f"[red]gh CLI error: {result.stderr.strip()}[/]", file=sys.stderr)
            return None
    except FileNotFoundError:
        print("[red]gh CLI not found. Install GitHub CLI: brew install gh[/]", file=sys.stderr)
        return None
    except subprocess.TimeoutExpired:
        print("[red]gh CLI timed out.[/]", file=sys.stderr)
        return None
